/*
 * This source file was generated by the Gradle 'init' task
 */
package de.malte.json4j;

/**
 * An item in a valid JSON string.
 */
public abstract class JsonElement {
    public String spell(JsonSpeller speller) {
        format(speller);
        return speller.toString();
    }
    abstract void format(JsonSpeller speller);
}
